USE [master]
GO

/****** Object:  Database [KOLBO]    Script Date: 22/08/2022 19:23:15 ******/
CREATE DATABASE [KOLBO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KOLBO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\KOLBO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'KOLBO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\KOLBO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KOLBO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [KOLBO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KOLBO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [KOLBO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [KOLBO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [KOLBO] SET ARITHABORT OFF 
GO

ALTER DATABASE [KOLBO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [KOLBO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KOLBO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KOLBO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KOLBO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KOLBO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [KOLBO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KOLBO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KOLBO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KOLBO] SET  DISABLE_BROKER 
GO

ALTER DATABASE [KOLBO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [KOLBO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KOLBO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KOLBO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KOLBO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KOLBO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KOLBO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [KOLBO] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [KOLBO] SET  MULTI_USER 
GO

ALTER DATABASE [KOLBO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KOLBO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [KOLBO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [KOLBO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [KOLBO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [KOLBO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [KOLBO] SET QUERY_STORE = OFF
GO

ALTER DATABASE [KOLBO] SET  READ_WRITE 
GO

